name: "Wait"
description: "Wait a designated number of milliseconds"
inputs:
  versionFile: # id of input
    description: "Path to version"
    required: true
  githubToken:
    description: "Github token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
